[package]
name = "sahara_mem"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
sahara = { path = "../sahara" }
