[package]
name = "upload_program"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
eg.workspace = true
sahara.workspace = true
anyhow = "1.0"
